FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -m appuser

RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 5000

CMD ["gunicorn","--bind","0.0.0.0:5000","app:app"]
