name: Employee Portal CI/CD

on:
  push:
    branches:
      - main

jobs:

  # =========================
  # FRONTEND DEPLOY (S3)
  # =========================
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/ s3://employee-portal-frontend-sachin --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

  # =========================
  # BACKEND DEPLOY (EC2)
  # =========================
  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend   # frontend success ke baad backend deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/employee-portal-devops

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies..."
            pip3 install -r backend/requirements.txt

            echo "Restarting services..."
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx

            echo "Backend deployment completed"